name: CommandSchedulerPlus
version: 2.2
description: A Minecraft plugin that schedules long term commands. https://www.spigotmc.org/resources/commandschedulerplus.51991/
author: Christian Ransom

main: muttsworld.dev.team.CommandSchedulerPlus.CommandSchedulerPlus

commands:
  csp:
    description: Main Command
    usage: /cps help
    aliases: [commandschedulerplus]
    permission: csp.admin