name: CommandSchedulerPlus
version: 2.1
description: A Minecraft plugin that schedules long term commands.
author: Christian Ransom

main: muttsworld.dev.team.CommandSchedulerPlus.CommandSchedulerPlus

commands:
  csp:
    description: Main Command
    usage: /cps help
    aliases: [commandschedulerplus]
    permission: csp.admin